- name: 清理旧数据
  shell: 'docker-compose -f {{ OPT_PTAH }}/docker-registry/docker-compose.yaml rm -fsva && rm -rf {{ OPT_PATH }}/docker-registry'
  ignore_errors: yes

- name: 预处理
  shell: '[[ ! -d "{{ OPT_PATH }}/docker-registry" ]] && mkdir -vp {{ OPT_PATH }}/docker-registry;
  [[ ! -d "{{ OPT_PATH }}/docker-registry/auth" ]] && mkdir -vp {{ OPT_PATH }}/docker-registry/auth'
  ignore_errors: yes

#- name: 制作自签署证书
  #shell: 'openssl req -newkey rsa:2048 -nodes -sha256 -keyout /opt/gengxiankun-galaxy/docker-registry/certs/{{ DOCKER_REGISTRY_CN }}.key -x509 -days 365 -out /opt/gengxiankun-galaxy/docker-registry/certs/{{ DOCKER_REGISTRY_CN }}.crt -subj "/C={{ DOCKER_REGISTRY_C }}/ST={{ DOCKER_REGISTRY_ST }}/L={{  DOCKER_REGISTRY_L }}/O={{ DOCKER_REGISTRY_O }}/OU={{ DOCKER_REGISTRY_OU }}/CN={{ DOCKER_REGISTRY_CN }}/emailAddress={{ DOCKER_REGISTRY_EMAIL_ADDRESS }}"'

- name: 生成鉴权密码文件
  shell: 'docker run --entrypoint htpasswd registry:2 -Bbn {{ DOCKER_REGISTRY_USER }} {{ DOCKER_REGISTRY_PASSWORD }}  > {{ OPT_PATH }}/docker-registry/auth/htpasswd'

- name: 配置docker-compose.yml
  template: src=docker-compose.yml.j2 dest={{ OPT_PATH }}/docker-registry/docker-compose.yml

- name: 启动服务
  shell: 'docker-compose -p registry -f {{ OPT_PATH }}/docker-registry/docker-compose.yml up -d'
